# Generated by Django 3.0.5 on 2021-02-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_title', models.CharField(max_length=255)),
                ('grammar_text', models.TextField(max_length=100000)),
            ],
        ),
    ]
